// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type City struct {
	ID        int    `json:"id"`
	Name      string `json:"name"`
	State     *State `json:"State"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
}

type Country struct {
	ID        int      `json:"id"`
	Name      string   `json:"name"`
	States    []*State `json:"States"`
	CreatedAt string   `json:"created_at"`
	UpdatedAt string   `json:"updated_at"`
}

type State struct {
	ID        int      `json:"id"`
	Name      string   `json:"name"`
	Country   *Country `json:"Country"`
	Cities    []*City  `json:"Cities"`
	CreatedAt string   `json:"created_at"`
	UpdatedAt string   `json:"updated_at"`
}
